### ISSUE TITLE
Add NPC Blocks

### ISSUE THREAD

**Issue by Caldeth** [sadovsf/StargateRPGSystem#11]
I'd love to see NPC blocks added as a character sheet Template. A simplified Character sheet for recording NPC's, similar to the ones at the back of the book. These could perhaps be on two tabbed pages, 1 the block and 2 portrait and description or just the one page with additional space for the portrait and description/notes.

I've attached a image as an example; https://imgur.com/a/0YhHJhG

**Comment by sadovsf** [comment]
Is there some difference between this and character sheet now? 🤔

We are actually just writing what is in these blocks as new character. What is missing there for sure are some GM notes for example 🤔

From my point of view, you need to have rolls and calculations working as well so from system point of view those are super similar 🤔

**Comment by Caldeth** [comment]
Really it’s just that stat blocks are a little simpler than full character sheets. It can be useful when you are using several different NPC types in one battle as you can have several open and easily see the stats,  relevant skills and special attacks/abilities all on one block.

You are right in that they are very similar to the existing character sheet, I just personally find the simplified block easier to use when handling several NPC’s

**Comment by sadovsf** [comment]
I see, I think I have some idea about how it should work then 🤔

Will try to find some way of how to make pretty much compact sheets for npcs 🤔 sounds pretty usefull 😊

**Comment by sadovsf** [comment]
Implemented in 07158aa

**Comment by Caldeth** [comment]
I just wanted to share this with you. Your new NPC cards works amazingly well with the GM screen Module. Thanks again for doing these! https://imgur.com/36hrOkB

**Comment by sadovsf** [comment]
Thank you for sharing this. It looks awesome!
Glad i could help 😊
