### ISSUE TITLE
Character sheet

### ISSUE THREAD

**Issue by Paladin1127** [sadovsf/StargateRPGSystem#16]
for some reason I am unable to open character sheets, I have tried with no modules and starting a clean world but I can't open the sheet

**Comment by sadovsf** [comment]
Thank you for report, could you maybe send console log from your browser after you try opening sheet? 

Also what browser are you using?

**Comment by Paladin1127** [comment]
I was using the foundry program directly

**Comment by sadovsf** [comment]
Ok that runs on chromium AFAIK. Try to open It in browser and send the logs please. I was working on system on weekend and it was working on my side

**Comment by Paladin1127** [comment]
Here is the error

foundry.js:2013 TypeError: An error occurred while rendering SGActorSheet
26: Cannot read properties of undefined (reading 'getFlag') at
Object.getTensionDie (sgrpg.js:89) at SGActorSheet.getData (actorSheet.js:53)
at SGActorSheet._render (foundry.js:2049) at SGActorSheet._render (
foundry.js:2736) at SGActorSheet.render (foundry.js:2011) at
SGActorSheet.render (foundry.js:3231) at ActorDirectory._onClickEntityName (
foundry.js:23917) at ActorDirectory._onClickEntityName (foundry.js:32414) at
HTMLOListElement.dispatch (jquery.min.js:2) at HTMLOListElement.v.handle (
jquery.min.js:2)
﻿

**Comment by sadovsf** [comment]
Great, thank you. Will take a look probably today after work. It should fairly easy fix

**Comment by sadovsf** [comment]
So it seems that issue is present when there is no active scene. Fix will be up in a few minutes. In mean time you should be able to fix it by adding scene and switching into it ;-)

b67c984df14b07c2ac13c47c8888d054be6e144c

**Comment by sadovsf** [comment]
So fix is released and should be available for update in foundry

**Comment by Paladin1127** [comment]
Got it working, any chance you will be adding gear or classes or feats to
the system

**Comment by sadovsf** [comment]
Great to hear it's working 😊

Iam allowed to add some gear but as this is only non payed project in my spare time iam not sure when will be this available. 

Me and my play group are using system on regular basis so I know at least basic gear like weapons and equipment is working quite well. It's just not distributed with system yet as I need to clean it up, organize it and ideally share it once system will be not changing (read improving or adding new features) that often. Also currently I don't have icons for many of items and I find it bad to include items Without icons and stuff. It would be bad for playing
