### ISSUE TITLE
Radiant and Sonic Damage

### ISSUE THREAD

**Issue by Caldeth** [sadovsf/StargateRPGSystem#19]
Please could you add Radiant and Sonic damage in the weapons category as these seem to be missing at the moment. Also would it be possible to select two damages types as some weapons like the Tacluchnatagamuntoron (Tac Grenade) inflict two damage types

**Comment by sadovsf** [comment]
Sure, adding new damage type is simple. Having more damage types not that simple but not hard either. I will try to add both in next update.

You can maybe use weapon special field for second damage type? 🤔

**Comment by sadovsf** [comment]
Added in 7cf0dab61742fade9bb00bc1524a7de6b03fc4c7
i will probably release update for public later with more stuff if its OK (you can simply download this repository and put it into systems folder if you want it right away ;-)

**Comment by Caldeth** [comment]
Perfect, thanks again for doing this, very much appreciated. :)

**Comment by sadovsf** [comment]
No problem :-)
Glad i could help ;-)
