### ISSUE TITLE
Add Armor as an item category

### ISSUE THREAD

**Issue by Caldeth** [sadovsf/StargateRPGSystem#20]
As well as Weapons and Equipment please could we have an Armour category with space to add AC, Bulk, Type etc.

**Comment by sadovsf** [comment]
I hear you. This would be bigger change in current system so iam not sure when I will be able to implement it (as I work on it in my spare time for free).

So I will gladly implement it. I just cannot promise when

**Comment by Caldeth** [comment]
There is no rush, I'm loving it as it is. Just wanted to make the suggestion. Currently I am using the equipment category and that works well for now :)

**Comment by sadovsf** [comment]
Glad you like it 😊
Let me know if you will have more ideas for improvements 😉

**Comment by sadovsf** [comment]
Believe implemented by https://github.com/sadovsf/StargateRPGSystem/pull/25
