### ISSUE TITLE
Missing Compendium items

### ISSUE THREAD

**Issue by Spaceferret42** [sadovsf/StargateRPGSystem#21]
Nothing shows up in compendium no races, origins, classes, feats, or equipment. I can also only make custom items or equipment so cannot just fill in the missing actor items

**Comment by sadovsf** [comment]
That is true, this is not any official system implementation and iam allowed only add few things into compendium for most of which I don't have icons. To play star gate, you need to own rule book and use that as guide to create items, equipment and characters.
