### ISSUE TITLE
Unable to create anything other then weapons and items

### ISSUE THREAD

**Issue by Spaceferret42** [sadovsf/StargateRPGSystem#22]
When trying to add things such as races, classes, or anything else not having to due with a weapon or equipment it is impossible due to these being the only addable categories.

**Comment by sadovsf** [comment]
Yes that is true, these are just entry fields in character sheet and it is as designed as I don't have capacity to implement all rules into it. Just create character sheet and fill it based on rules and your chosen races etc..
