### ISSUE TITLE
How to add to inventory

### ISSUE THREAD

**Issue by jermainelecky** [sadovsf/StargateRPGSystem#24]
This is most likely a user error as I'm new to Foundry, but I can't seem to figure out how to add weapons and equipment to my inventory. there isn't an edit button in the Inventory section of the character sheet like the other sections of the Background tab has. I thought maybe I had to create an item first then it would show up somewhere to equip it, but I don't see that either. can you please instruct me on how to do this? Thanks!!

**Comment by sadovsf** [comment]
Works same way as in 5e system. You just create item and then drag and drop it onto character sheet which places it into proper inventory based on type (equip or weapons) 😉
